import { TextEncoder, TextDecoder } from 'node:util';
import { ReadableStream, WritableStream, TransformStream } from 'node:stream/web';
import { MessageChannel, MessagePort } from 'node:worker_threads';
Object.defineProperty(globalThis, 'TextEncoder', { value: TextEncoder, writable: true });
Object.defineProperty(globalThis, 'TextDecoder', { value: TextDecoder, writable: true });
Object.defineProperty(globalThis, 'ReadableStream', { value: ReadableStream, writable: true });
Object.defineProperty(globalThis, 'WritableStream', { value: WritableStream, writable: true });
Object.defineProperty(globalThis, 'TransformStream', { value: TransformStream, writable: true });
Object.defineProperty(globalThis, 'MessageChannel', { value: MessageChannel, writable: true });
Object.defineProperty(globalThis, 'MessagePort', { value: MessagePort, writable: true });
import '@testing-library/jest-dom';
import { fetch, Request, Response, Headers } from 'undici';
Object.defineProperty(globalThis, 'fetch', { value: fetch, writable: true });
Object.defineProperty(globalThis, 'Request', { value: Request, writable: true });
Object.defineProperty(globalThis, 'Response', { value: Response, writable: true });
Object.defineProperty(globalThis, 'Headers', { value: Headers, writable: true });
