name: Security Baseline

on:
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Secrets scan
        run: GIT_CI=1 node scripts/security.secrets.scan.mjs
      - name: CI hygiene
        run: GIT_CI=1 node scripts/security.ci.hygiene.mjs
      - name: Dotenv lint
        run: GIT_CI=1 node scripts/security.dotenv.lint.mjs
