name: CI
on:
  push:
    branches: [ main, "**" ]
  pull_request:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm -w test
  web-smoke:
    name: web-smoke
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Restore Next.js cache (.next/cache)
        id: next_cache
        uses: actions/cache@v4
        with:
          path: apps/web/.next/cache
          key: ${{ runner.os }}-nextcache-web-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('apps/web/next.config.*','apps/web/tsconfig.json','apps/web/package.json') }}
          restore-keys: |
            ${{ runner.os }}-nextcache-web-
      - name: Measure & run web smoke
        id: smoke_timed
        shell: bash
        env:
          ART_DIR: artifacts/${{ github.run_id }}
        run: |
          set -euo pipefail
          mkdir -p "$ART_DIR"
          start_ts=$(date +%s)
          if [ -x apps/web/tools/smoke.portable.sh ]; then
            apps/web/tools/smoke.portable.sh --ci
          else
            apps/web/tools/smoke.sh --ci
          fi
          end_ts=$(date +%s)
          total=$(( end_ts - start_ts ))
          echo "$total" > "$ART_DIR/web_smoke_total_seconds.txt"
          echo "total_seconds=$total" >> "$GITHUB_OUTPUT"
      - name: Upload STEP41 artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: step41-smoke-timings-${{ github.run_id }}
          path: artifacts/${{ github.run_id }}/*
      - name: STEP41 · Summary
        if: always()
        shell: bash
        run: |
          {
            echo "## STEP41 · Next.js cache experiment & timing"
            echo ""
            if [ "${{ steps.next_cache.outputs.cache-hit }}" = "true" ]; then
              echo "- Cache restore: **HIT**"
            else
              echo "- Cache restore: **MISS**"
            fi
            echo "- web-smoke total (build+boot): **${{ steps.smoke_timed.outputs.total_seconds }}s**"
          } >> "$GITHUB_STEP_SUMMARY"
