name: CI

on:
  push:
    branches: [ main, "**" ]
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm -w test

  web-smoke:
    name: web-smoke
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Start timer
        id: start_timer
        run: echo "START_TS=$(date +%s)" >> $GITHUB_ENV

      - name: Run smoke
        run: |
          pnpm --filter @iberitax/web smoke:portable

      - name: Stop timer and save timing artifact
        if: always()
        run: |
          END_TS=$(date +%s)
          TOTAL=$((END_TS - START_TS))
          mkdir -p artifacts/${{ github.run_id }}
          echo "$TOTAL" > artifacts/${{ github.run_id }}/web_smoke_total_seconds.txt
          printf "web-smoke total seconds: %s\n" "$TOTAL" >> $GITHUB_STEP_SUMMARY

      - name: Upload timing artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-smoke-timing-${{ github.run_id }}
          path: artifacts/${{ github.run_id }}/web_smoke_total_seconds.txt
          if-no-files-found: error
