name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ensure pnpm
        run: npm i -g pnpm@9.11.0 && pnpm -v

      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Setup pnpm
          cache: 'pnpm'

      - name: Activate pnpm
        run: corepack enable && corepack prepare pnpm@9.11.0 --activate && pnpm -v
      - name: Setup pnpm

      - name: Run extractor tests (golden + snapshots + integration)
        run: pnpm -C packages/extractor test

  web-smoke:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ensure pnpm
        run: npm i -g pnpm@9.11.0 && pnpm -v

      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Setup pnpm

      - name: Setup pnpm

      - name: Build web
        run: pnpm -C apps/web build

      - name: Start web
        run: pnpm --filter @iberitax/web exec next start -p 3001 &

      - name: Smoke test
        env:
          BASE_URL: http://localhost:3001
        run: apps/web/tools/smoke.portable.sh

      - name: Stop web
        if: always()
        run: lsof -ti tcp:3001 | xargs kill -9 || true
