name: OCR Validate

on:
  pull_request:
  workflow_dispatch:

jobs:
  ocr-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build + Contracts
        run: |
          pnpm -F @iberitax/ocr build
          pnpm -F @iberitax/ocr run test:contracts || true

      - name: Rebuild history
        run: pnpm -F @iberitax/ocr run post:ocr:history

      - name: Optional drift gate
        env:
          GATE_DRIFT: ${{ vars.GATE_DRIFT }}
        run: pnpm -F @iberitax/ocr run check:contracts:drift

      - name: PR Summary (sparkline)
        run: node .github/scripts/ocr-summary.mjs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ocr-history-and-trend
          path: |
            packages/ocr/artifacts/validation_history.md
            packages/ocr/artifacts/validation_trend.md
            packages/ocr/artifacts/history
          if-no-files-found: warn
