name: Publish Rules Dashboard Bundle

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: [ "v*" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      stamp: ${{ steps.stamp.outputs.stamp }}
      refname: ${{ steps.stamp.outputs.refname }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Prebuild rules dashboard
        env:
          ENABLE_RULES_DASHBOARD: 1
          ENABLE_RULE_INSIGHTS_HTML: 1
        shell: bash
        run: |
          mkdir -p artifacts/modelo100
          [ -f artifacts/modelo100/rules.index.md ] || cat > artifacts/modelo100/rules.index.md <<'MD'
          | id | tags | message | severity |
          |----|------|---------|----------|
          MD
          node scripts/modelo100.rules.index.mjs || true
          node scripts/modelo100.rules.index.html.mjs || true
          node scripts/modelo100.rules.insights.html.mjs || true
          node scripts/modelo100.rules.dashboard.html.mjs || true

      - name: Build publish bundle
        env:
          ENABLE_RULES_PUBLISH: 1
        shell: bash
        run: |
          node -v
          node scripts/modelo100.rules.publish.mjs
          test -f artifacts/modelo100/rules-dashboard-bundle.zip
          echo "::notice title=Bundle Found::artifacts/modelo100/rules-dashboard-bundle.zip"

      - name: Compute build stamp
        id: stamp
        shell: bash
        run: |
          TS=$(date -u +%Y%m%dT%H%M%SZ)
          SHA=$(git rev-parse --short HEAD)
          REF="${GITHUB_REF_NAME}"
          echo "stamp=${TS}-${SHA}" >> "$GITHUB_OUTPUT"
          echo "refname=${REF}" >> "$GITHUB_OUTPUT"
          echo "::notice title=Build Stamp::${TS}-${SHA}"

      - name: Prepare release files
        shell: bash
        run: |
          mkdir -p artifacts/release
          cp artifacts/modelo100/rules-dashboard-bundle.zip "artifacts/release/rules-dashboard-bundle-${{ steps.stamp.outputs.stamp }}.zip"
          sed -e "s/{{TAG}}/${{ steps.stamp.outputs.refname }}/g" -e "s/{{STAMP}}/${{ steps.stamp.outputs.stamp }}/g" docs/publish-notes.md > artifacts/release/release-notes.md
          ls -l artifacts/release

      - uses: actions/upload-artifact@v4
        with:
          name: rules-dashboard-bundle-${{ steps.stamp.outputs.stamp }}
          path: artifacts/release/*

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload site to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: artifacts/modelo100/dist

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
